default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/dev-five-minutes-idea
  username: <%= Rails.application.secrets.db[:user] %>
  password: <%= Rails.application.secrets.db[:pass] %>

test:
  <<: *default
  database: db/test-five-minutes-idea

production:
  <<: *default
  database: db/prod-five-minutes-idea
