default: &default
  adapter: postgrsql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/dev-five-minutes-idea
  username: <%= Rails.application.secrets.database[:username] %>
  password: <%= Rails.application.secrets.database[:password] %>

test:
  <<: *default
  database: db/test-five-minutes-idea

production:
  <<: *default
  database: db/prod-five-minutes-idea
